
CREATE DATABASE IF NOT EXISTS escaperoomdb;
USE escaperoomdb;

CREATE TABLE IF NOT EXISTS Room (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    difficulty ENUM('EASY', 'NORMAL', 'HARD', 'VERY_HARD') NOT NULL,
    price DOUBLE NOT NULL,
    quantity INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Clue (
    id INT AUTO_INCREMENT PRIMARY KEY,
    theme ENUM('MYSTERY', 'HORROR', 'SCI_FI', 'ADVENTURE') NOT NULL,
    price DOUBLE NOT NULL,
    quantity INT NOT NULL
);

CREATE TABLE IF NOT EXISTS DecorationItem (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    materialType VARCHAR(50) NOT NULL,
    price DOUBLE NOT NULL,
    quantity INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Player (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS EscapeRoom (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    totalInventoryValue DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS SalesTicket (
    id INT AUTO_INCREMENT PRIMARY KEY,
    playerId INT NOT NULL,
    saleDate DATE NOT NULL,
    total DOUBLE NOT NULL,
    FOREIGN KEY (playerId) REFERENCES Player(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CompletionCertificate (
    id INT AUTO_INCREMENT PRIMARY KEY,
    playerId INT NOT NULL,
    issueDate DATE NOT NULL,
    achievements TEXT,
    gift VARCHAR(100),
    FOREIGN KEY (playerId) REFERENCES Player(id) ON DELETE CASCADE
);
